### ISSUE TITLE
Lost tag for 1.4.2

### ISSUE THREAD

**Issue by crisp-github** [Setasign/FPDI-TCPDF#1]
Hi,

Our composer.json has:

"setasign/fpdi": "1.4.2"

But this is no longer available. Is there a reason to remove that tag ? 

Thanks.

**Comment by JanSlabon** [comment]
Hi !

Our vendor name was "hijacked" in the past. The version you are referencing was never officially released by us (it was a modified version). Furthermore the version is more than 4 years old, so an update is recommended, which will not come with any BC issues.

Cheers,
Jan

**Comment by crisp-github** [comment]
Hi,

Unfortunately there are BC issues. Hard to understand what is going on but FPDI was picking up TCPDF with version 1.4.2 After updating it no longer works. Seems to be something about the ordering of the autoloading. I added an explicit require of tcpdf.php and that seems to have fixed at least one problem. 

Cheers,
   Mark

**Comment by JanSlabon** [comment]
FPDI itself has no dependencies (in its main package) as you can use it with both FPDF or TCPDF. The version you are refering to was never an official version and exactly this hard dependency was a problem for us, to keep this version. If you need to use TCPDF, just try out this package: https://packagist.org/packages/setasign/fpdi-tcpdf

**Comment by JanSlabon** [comment]
Follow this issue here: https://github.com/Setasign/FPDI/issues/3
